name: backend-pipeline

on:
  push:
    branches:
      - main
concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: clone code repository
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install
        working-directory: ./backend

      - name: run unit tests
        run: npm test
        working-directory: ./backend
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: clone code repository
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t chouchenechadha/covoiturage-backend:${{ github.sha }} .
        working-directory: ./backend

      - name: check image
        run: docker images

      - name: log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image
        run: |
              docker push chouchenechadha/covoiturage-backend:${{ github.sha }}
              docker tag chouchenechadha/covoiturage-backend:${{ github.sha }} chouchenechadha/covoiturage-backend:latest
              docker push chouchenechadha/covoiturage-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: collect via ssh and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd ~/svc_core/devops-script

            docker pull chouchenechadha/covoiturage-backend:latest
            docker compose up -d backend

            sudo systemctl restart svcpro