name: backend-pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: clone code repository
        uses: actions/checkout@v4
      - name : intall dependencies
        run: npm install
        working-directory: ./backend

      - name: run unit tests
        run: npm test
        working-directory: ./backend